/**
 * ds-components.jsx — Lingua DS live token + component explorer
 *
 * Runs in-browser via Babel standalone (no bundler required).
 * Reads design data from window.LDS (set by tokens-export.js, generated by the build).
 *
 * Phase 4: repointed from hand-written values to window.LDS.tokens / window.LDS.cssVars.
 * "View source" in a browser shows the raw JSX — intentional design artifact.
 */

const { useState, useEffect, useMemo } = React;

// ─── Utilities ────────────────────────────────────────────────────────────────

function readCssVar(name) {
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
}

function isColorValue(val) {
  return typeof val === 'string' && (val.startsWith('#') || val.startsWith('rgb') || val.startsWith('hsl'));
}

function contrastColor(hex) {
  const r = parseInt(hex.slice(1,3), 16);
  const g = parseInt(hex.slice(3,5), 16);
  const b = parseInt(hex.slice(5,7), 16);
  return (r*299 + g*587 + b*114) / 1000 > 128 ? '#0f172a' : '#ffffff';
}

// ─── Components ───────────────────────────────────────────────────────────────

function ColorSwatch({ cssVar, value, label }) {
  const [copied, setCopied] = useState(false);

  function copy() {
    navigator.clipboard?.writeText(cssVar).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1400);
    });
  }

  const live = readCssVar(cssVar) || value;
  const textColor = live.startsWith('#') && live.length === 7 ? contrastColor(live) : 'var(--color-foreground)';

  return (
    <div className="ds-token-card" title={`Click to copy ${cssVar}`} onClick={copy} style={{ cursor: 'pointer' }}>
      <div
        className="ds-token-card__swatch"
        style={{ background: live, display: 'flex', alignItems: 'center', justifyContent: 'center' }}
      >
        {copied && (
          <span style={{ fontSize: 11, fontWeight: 700, color: textColor, letterSpacing: '0.04em' }}>COPIED</span>
        )}
      </div>
      <div className="ds-token-card__body">
        <p className="ds-token-card__var">{cssVar}</p>
        <p className="ds-token-card__val">{live || value}</p>
        {label && <p className="ds-token-card__var" style={{ marginTop: 2 }}>{label}</p>}
      </div>
    </div>
  );
}

function SemanticPalette({ tokens }) {
  if (!tokens) return null;
  const lightTokens = Object.entries(tokens.light || {});
  const colorTokens = lightTokens.filter(([k]) => k.startsWith('light.color.'));

  return (
    <section>
      <h2>Semantic Colours</h2>
      <p className="ds-section-desc">
        These CSS vars switch between light and dark mode automatically.
        Toggle the theme button to see the values update live.
      </p>
      <div className="ds-token-grid">
        {colorTokens.map(([path, entry]) => {
          const cssVar = entry.cssVar;
          const label  = path.replace('light.color.', '');
          return (
            <ColorSwatch
              key={path}
              cssVar={cssVar}
              value={String(entry.value)}
              label={label}
            />
          );
        })}
      </div>
    </section>
  );
}

function GlobalPalette({ tokens }) {
  if (!tokens) return null;
  const globalTokens = Object.entries(tokens.global || {});
  const colorTokens  = globalTokens.filter(([k]) => k.startsWith('global.color.'));

  // Group by color scale (primary, neutral, success, …)
  const groups = {};
  colorTokens.forEach(([path, entry]) => {
    const parts = path.replace('global.color.', '').split('.');
    const group = parts[0];
    groups[group] = groups[group] || [];
    groups[group].push({ path, entry, shade: parts[1] });
  });

  return (
    <section>
      <h2>Global Palette</h2>
      <p className="ds-section-desc">
        Primitive colour scales available as <code>--global-color-*</code> CSS vars.
        Click any swatch to copy its custom property name.
      </p>
      {Object.entries(groups).map(([group, shades]) => (
        <div key={group} style={{ marginBottom: 24 }}>
          <h3 style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-muted-fg)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 10 }}>
            {group}
          </h3>
          <div className="ds-token-grid">
            {shades.map(({ path, entry, shade }) => (
              <ColorSwatch
                key={path}
                cssVar={entry.cssVar}
                value={String(entry.value)}
                label={shade}
              />
            ))}
          </div>
        </div>
      ))}
    </section>
  );
}

function TypographyScale({ tokens }) {
  if (!tokens) return null;
  const fontSizes = Object.entries(tokens.global || {})
    .filter(([k]) => k.startsWith('global.fontSize.'))
    .map(([k, v]) => ({ name: k.replace('global.fontSize.', ''), value: v.value, cssVar: v.cssVar }))
    .sort((a, b) => parseFloat(a.value) - parseFloat(b.value));

  const fontFamilies = Object.entries(tokens.global || {})
    .filter(([k]) => k.startsWith('global.fontFamily.'))
    .map(([k, v]) => ({ name: k.replace('global.fontFamily.', ''), value: v.value, cssVar: v.cssVar }));

  return (
    <section>
      <h2>Typography</h2>
      <p className="ds-section-desc">Font sizes from <code>--global-font-size-*</code>. Headings use the serif stack; body uses sans.</p>

      <div className="ds-type-scale" style={{ marginBottom: 32 }}>
        {fontSizes.map(t => (
          <div className="ds-type-row" key={t.name}>
            <span className="ds-type-row__label">{t.name}</span>
            <span
              className="ds-type-row__sample"
              style={{ fontSize: t.value, lineHeight: 1.2, fontFamily: 'var(--font-sans)' }}
            >
              The quick brown fox — {t.value}
            </span>
          </div>
        ))}
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {fontFamilies.map(t => (
          <div key={t.name} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            <code style={{ minWidth: 48, fontSize: 12, color: 'var(--color-muted-fg)' }}>{t.name}</code>
            <span style={{ fontFamily: t.value, fontSize: 16 }}>Lingua Design System — {t.name}</span>
          </div>
        ))}
      </div>
    </section>
  );
}

function SpacingScale({ tokens }) {
  if (!tokens) return null;
  const spacingTokens = Object.entries(tokens.global || {})
    .filter(([k]) => k.startsWith('global.spacing.'))
    .map(([k, v]) => ({ name: k.replace('global.spacing.', ''), value: v.value, cssVar: v.cssVar }))
    .sort((a, b) => parseFloat(a.value) - parseFloat(b.value));

  return (
    <section>
      <h2>Spacing</h2>
      <p className="ds-section-desc">4-point grid. All values available as <code>--global-spacing-*</code> CSS vars and in the Tailwind preset.</p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {spacingTokens.map(t => (
          <div key={t.name} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
            <code style={{ minWidth: 200, fontSize: 12, color: 'var(--color-muted-fg)' }}>{t.cssVar}</code>
            <div style={{
              height: 12, borderRadius: 99, background: 'var(--color-primary)',
              width: t.value, minWidth: 4, transition: 'width 0.3s',
            }} />
            <span style={{ fontSize: 12, color: 'var(--color-muted-fg)' }}>{t.value}</span>
          </div>
        ))}
      </div>
    </section>
  );
}

function ShadowScale({ tokens }) {
  if (!tokens) return null;
  const shadows = Object.entries(tokens.global || {})
    .filter(([k]) => k.startsWith('global.shadow.'))
    .map(([k, v]) => ({ name: k.replace('global.shadow.', ''), value: String(v.value), cssVar: v.cssVar }));

  return (
    <section>
      <h2>Shadows</h2>
      <p className="ds-section-desc">Box shadow tokens, available as <code>--global-shadow-*</code> CSS vars and in the Tailwind <code>boxShadow</code> scale.</p>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16 }}>
        {shadows.map(t => (
          <div key={t.name} style={{
            padding: 24, borderRadius: 16, background: 'var(--color-card)',
            border: '1px solid var(--color-border)', boxShadow: t.value, minWidth: 140,
          }}>
            <p style={{ fontSize: 14, fontWeight: 600, color: 'var(--color-foreground)', marginBottom: 4 }}>{t.name}</p>
            <code style={{ fontSize: 11, color: 'var(--color-muted-fg)' }}>{t.cssVar}</code>
          </div>
        ))}
      </div>
    </section>
  );
}

function ComponentRegistry() {
  const components = [
    { name: 'Button',        group: 'Primitives',  path: 'Button/Button' },
    { name: 'Badge',         group: 'Primitives',  path: 'Badge/Badge' },
    { name: 'Pill',          group: 'Primitives',  path: 'Pill/Pill' },
    { name: 'Tag',           group: 'Primitives',  path: 'Tag/Tag' },
    { name: 'Avatar',        group: 'Primitives',  path: 'Avatar/Avatar' },
    { name: 'Card',          group: 'Surfaces',    path: 'Card/Card' },
    { name: 'Sheet',         group: 'Surfaces',    path: 'Sheet/Sheet' },
    { name: 'TextField',     group: 'Inputs',      path: 'TextField/TextField' },
    { name: 'Select',        group: 'Inputs',      path: 'Select/Select' },
    { name: 'Checkbox',      group: 'Inputs',      path: 'Checkbox/Checkbox' },
    { name: 'RadioGroup',    group: 'Inputs',      path: 'RadioGroup/RadioGroup' },
    { name: 'Switch',        group: 'Inputs',      path: 'Switch/Switch' },
    { name: 'ProgressBar',   group: 'Feedback',    path: 'ProgressBar/ProgressBar' },
    { name: 'Spinner',       group: 'Feedback',    path: 'Spinner/Spinner' },
    { name: 'Toast',         group: 'Feedback',    path: 'Toast/Toast' },
    { name: 'BottomNav',     group: 'Navigation',  path: 'BottomNav/BottomNav' },
    { name: 'TopBar',        group: 'Navigation',  path: 'TopBar/TopBar' },
    { name: 'Flashcard',     group: 'Domain',      path: 'Flashcard/Flashcard' },
    { name: 'CategoryChip',  group: 'Domain',      path: 'CategoryChip/CategoryChip' },
    { name: 'StreakCounter',  group: 'Domain',      path: 'StreakCounter/StreakCounter' },
    { name: 'MasteryMeter',  group: 'Domain',      path: 'MasteryMeter/MasteryMeter' },
  ];

  const groups = [...new Set(components.map(c => c.group))];

  return (
    <section>
      <h2>Components</h2>
      <p className="ds-section-desc">
        All 21 components exported from <code>@lingua/react</code>.
        Live interactive demos are in{' '}
        <a href="../components/" style={{ color: 'var(--color-primary)' }}>Storybook ↗</a>.
      </p>
      {groups.map(group => (
        <div key={group} style={{ marginBottom: 24 }}>
          <h3 style={{ fontSize: 13, fontWeight: 600, color: 'var(--color-muted-fg)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 10 }}>
            {group}
          </h3>
          <div className="ds-component-grid">
            {components.filter(c => c.group === group).map(c => (
              <div key={c.name} className="ds-component-card">
                <p className="ds-component-card__name">{c.name}</p>
                <p className="ds-component-card__path">src/components/{c.path}.tsx</p>
                <span className="ds-component-card__badge">{group}</span>
              </div>
            ))}
          </div>
        </div>
      ))}
    </section>
  );
}

// ─── Root App ─────────────────────────────────────────────────────────────────

function TokenExplorer() {
  const [ready, setReady] = useState(Boolean(window.LDS));

  useEffect(() => {
    if (!window.LDS) {
      const timer = setInterval(() => {
        if (window.LDS) { setReady(true); clearInterval(timer); }
      }, 100);
      return () => clearInterval(timer);
    }
  }, []);

  if (!ready) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '60vh', color: 'var(--color-muted-fg)', flexDirection: 'column', gap: 16 }}>
        <div style={{ width: 32, height: 32, border: '3px solid var(--color-muted)', borderTopColor: 'var(--color-primary)', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} />
        <p>Loading token data…</p>
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  const { tokens } = window.LDS;

  return (
    <div className="ds-explorer">
      <div style={{ marginBottom: 48 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 8 }}>
          <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: 36, fontWeight: 700, color: 'var(--color-foreground)' }}>
            Token Explorer
          </h1>
          <span style={{
            padding: '3px 12px', borderRadius: 99, fontSize: 12, fontWeight: 600,
            background: 'color-mix(in srgb, var(--color-primary) 10%, transparent)',
            color: 'var(--color-primary)',
          }}>
            Phase 4 — live
          </span>
        </div>
        <p style={{ color: 'var(--color-muted-fg)', maxWidth: 560 }}>
          All values are read live from <code>window.LDS</code> (generated by{' '}
          <code>pnpm tokens:build</code> from <code>tokens/lingua-tokens.json</code>).
          Click any colour swatch to copy its CSS custom property name.
        </p>
      </div>

      <SemanticPalette tokens={tokens} />
      <GlobalPalette   tokens={tokens} />
      <TypographyScale tokens={tokens} />
      <SpacingScale    tokens={tokens} />
      <ShadowScale     tokens={tokens} />
      <ComponentRegistry />
    </div>
  );
}

ReactDOM.createRoot(document.getElementById('root')).render(<TokenExplorer />);
