/**
 * Phase 1 stub — copies source token JSON to dist so the build pipeline has
 * something to reference. Full Style Dictionary build is wired in Phase 2.
 */
import { readFileSync, mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '../../../');
const src  = resolve(root, 'tokens/lingua-tokens.json');
const pkg  = resolve(__dirname, '..');

const tokens = JSON.parse(readFileSync(src, 'utf8'));

const dirs = [
  `${pkg}/dist`,
  `${pkg}/dist/css`,
  `${pkg}/dist/js`,
  `${pkg}/dist/tailwind`,
  `${pkg}/dist/figma`,
];
dirs.forEach(d => mkdirSync(d, { recursive: true }));

// Copy raw token source
copyFileSync(src, `${pkg}/dist/figma/lingua-figma-tokens.json`);

// CSS stub — will be generated by Style Dictionary in Phase 2
const cssVarStub = `/* Auto-generated by @lingua/tokens — Phase 2 will replace this stub */
/* Run: pnpm tokens:build */
:root {
  --color-primary: #4f46e5;
  --color-background: #f8fafc;
  --color-foreground: #0f172a;
  --color-card: #ffffff;
  --color-muted: #f1f5f9;
  --color-muted-fg: #64748b;
  --color-border: #e2e8f0;
  --color-destructive: #ef4444;
}
`;
writeFileSync(`${pkg}/dist/css/lingua.light.css`, cssVarStub);
writeFileSync(`${pkg}/dist/css/lingua.dark.css`, `[data-theme="dark"] {\n  --color-primary: #818cf8;\n  --color-background: #020617;\n  --color-foreground: #f8fafc;\n  --color-card: #0f172a;\n  --color-muted: #1e293b;\n  --color-muted-fg: #94a3b8;\n  --color-border: #1e293b;\n  --color-destructive: #dc2626;\n}\n`);

// JS stub
writeFileSync(`${pkg}/dist/js/tokens.js`, `"use strict";\nObject.defineProperty(exports, "__esModule", { value: true });\nexports.tokens = ${JSON.stringify(tokens, null, 2)};\n`);
writeFileSync(`${pkg}/dist/js/tokens.mjs`, `export const tokens = ${JSON.stringify(tokens, null, 2)};\n`);
writeFileSync(`${pkg}/dist/js/tokens.d.ts`, `export declare const tokens: Record<string, unknown>;\n`);

// Tailwind preset stub
writeFileSync(`${pkg}/dist/tailwind/lingua.tailwind.js`, `/** Phase 2 will generate this from tokens. */\nmodule.exports = { theme: { extend: {} } };\n`);

console.log('✓  @lingua/tokens — Phase 1 stub build complete (Style Dictionary build ships in Phase 2)');
