/**
 * token-diff.mjs — Compute a human-readable diff between two token JSON files.
 *
 * Usage (called from CI):
 *   node scripts/token-diff.mjs <before.json> <after.json>
 *
 * Outputs a Markdown table comparing changed token values, suitable for a
 * GitHub PR comment body.
 */

import { readFileSync } from 'node:fs';

const [,, beforePath, afterPath] = process.argv;

if (!beforePath || !afterPath) {
  console.error('Usage: node token-diff.mjs <before.json> <after.json>');
  process.exit(1);
}

function flatten(obj, prefix = '') {
  return Object.entries(obj).flatMap(([key, val]) => {
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && !Array.isArray(val) && 'value' in val) {
      return [{ path, value: val.value, type: val.type }];
    }
    if (val && typeof val === 'object' && !Array.isArray(val)) {
      return flatten(val, path);
    }
    return [];
  });
}

let before, after;
try {
  before = JSON.parse(readFileSync(beforePath, 'utf8'));
  after  = JSON.parse(readFileSync(afterPath,  'utf8'));
} catch (err) {
  console.error(`Could not read files: ${err.message}`);
  process.exit(1);
}

const beforeFlat = Object.fromEntries(flatten(before).map(t => [t.path, t]));
const afterFlat  = Object.fromEntries(flatten(after).map(t => [t.path, t]));

const allPaths = new Set([...Object.keys(beforeFlat), ...Object.keys(afterFlat)]);

const added    = [];
const removed  = [];
const changed  = [];

for (const path of allPaths) {
  const b = beforeFlat[path];
  const a = afterFlat[path];

  if (!b)                                      added.push({ path, value: a.value, type: a.type });
  else if (!a)                                 removed.push({ path, value: b.value, type: b.type });
  else if (String(b.value) !== String(a.value)) changed.push({ path, before: b.value, after: a.value, type: a.type });
}

// ─── Markdown output ─────────────────────────────────────────────────────────

const lines = [];

lines.push('## 🎨 Token Diff\n');

if (changed.length === 0 && added.length === 0 && removed.length === 0) {
  lines.push('No token values changed.');
  console.log(lines.join('\n'));
  process.exit(0);
}

function colorSwatch(hex) {
  if (typeof hex !== 'string' || !hex.startsWith('#')) return '';
  return `![](https://singlecolorimage.com/get/${hex.slice(1)}/12x12)`;  // 12×12 color swatch
}

if (changed.length > 0) {
  lines.push(`### Changed (${changed.length})\n`);
  lines.push('| Token | Before | After |');
  lines.push('|---|---|---|');
  for (const { path, before: bv, after: av } of changed.slice(0, 50)) {
    const bSwatch = colorSwatch(String(bv));
    const aSwatch = colorSwatch(String(av));
    lines.push(`| \`${path}\` | ${bSwatch} \`${bv}\` | ${aSwatch} \`${av}\` |`);
  }
  if (changed.length > 50) lines.push(`\n_…and ${changed.length - 50} more._`);
  lines.push('');
}

if (added.length > 0) {
  lines.push(`### Added (${added.length})\n`);
  lines.push('| Token | Value |');
  lines.push('|---|---|');
  for (const { path, value } of added.slice(0, 20)) {
    lines.push(`| \`${path}\` | \`${value}\` |`);
  }
  if (added.length > 20) lines.push(`\n_…and ${added.length - 20} more._`);
  lines.push('');
}

if (removed.length > 0) {
  lines.push(`### Removed (${removed.length})\n`);
  lines.push('| Token | Was |');
  lines.push('|---|---|');
  for (const { path, value } of removed.slice(0, 20)) {
    lines.push(`| ~~\`${path}\`~~ | ~~\`${value}\`~~ |`);
  }
  if (removed.length > 20) lines.push(`\n_…and ${removed.length - 20} more._`);
  lines.push('');
}

lines.push('---');
lines.push('_Generated by `pnpm token-diff` · [View Storybook artifact in CI](../../actions)_');

console.log(lines.join('\n'));
